apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
    kompose.init.containers.command: '''sh'', ''-c'', ''until nc -z config-server:8888; do echo waiting for config-server; sleep 2; done;'''
    kompose.init.containers.image: busybox
    kompose.init.containers.name: init-config-server
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o petclinic_chart/templates
        kompose.image-pull-secret: regcred
        kompose.init.containers.command: '''sh'', ''-c'', ''until nc -z config-server:8888; do echo waiting for config-server; sleep 2; done;'''
        kompose.init.containers.image: busybox
        kompose.init.containers.name: init-config-server
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: discovery-server
    spec:
      containers:
        - image: '{{ .Values.IMAGE_TAG_DISCOVERY_SERVER }}'
          name: discovery-server
          ports:
            - containerPort: 8761
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      initContainers:
        - command:
            - sh
            - -c
            - until nc -z config-server:8888; do echo waiting for config-server; sleep 2; done;
          image: busybox
          name: init-config-server
      restartPolicy: Always
